# Generated by scripts/release.py (release-kit) from the v2026.10.1 release — do not edit.
class RefactorDsl < Formula
  desc "A DSL for multi-language code refactoring with Git-aware matching"
  homepage "https://github.com/grahambrooks/refactor-dsl"
  version "2026.10.1"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/grahambrooks/refactor-dsl/releases/download/v2026.10.1/refactor-v2026.10.1-aarch64-apple-darwin.tar.gz"
      sha256 "692cdd981eed403ab84bb9e86bdd46969730acfe519fb2f7a515bd17edb2071b"
    end
    on_intel do
      url "https://github.com/grahambrooks/refactor-dsl/releases/download/v2026.10.1/refactor-v2026.10.1-x86_64-apple-darwin.tar.gz"
      sha256 "4613a58705697632da3e965a934f3463160f6b4f5756ea2dfe07188ef5f808ec"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/grahambrooks/refactor-dsl/releases/download/v2026.10.1/refactor-v2026.10.1-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "97bddc0dcf537bd085faa73af08ee6e8e5df63354f46fa3324f87f4f60196810"
    end
    on_intel do
      url "https://github.com/grahambrooks/refactor-dsl/releases/download/v2026.10.1/refactor-v2026.10.1-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "f3f69d30945275f389fc3a8b7cc2496601750a51907bde0fd3f7c74a3ff55f7f"
    end
  end

  def install
    bin.install "refactor"
  end

  test do
    assert_path_exists bin/"refactor"
  end
end
