# Generated by scripts/release.py (release-kit) from the v2026.9.4 release — do not edit.
class RefactorDsl < Formula
  desc "A DSL for multi-language code refactoring with Git-aware matching"
  homepage "https://github.com/grahambrooks/refactor-dsl"
  version "2026.9.4"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/grahambrooks/refactor-dsl/releases/download/v2026.9.4/refactor-v2026.9.4-aarch64-apple-darwin.tar.gz"
      sha256 "172fc80da70884d2c94989c0cc7d0af5aefdfe562ad670ea4b68f30f5022c8a0"
    end
    on_intel do
      url "https://github.com/grahambrooks/refactor-dsl/releases/download/v2026.9.4/refactor-v2026.9.4-x86_64-apple-darwin.tar.gz"
      sha256 "3ded72464ef53dd49a4777098c40625e56360264c8a4d958969a883041b92616"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/grahambrooks/refactor-dsl/releases/download/v2026.9.4/refactor-v2026.9.4-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "86fc7a852851ded32ef63cf79b8bf508d61e157902a8aa7d83ff1cb41f94059d"
    end
    on_intel do
      url "https://github.com/grahambrooks/refactor-dsl/releases/download/v2026.9.4/refactor-v2026.9.4-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "e2f65dde7a83dd080bc2a5c2acb1826e0e7d3b9880e495f6b02d211712e5b971"
    end
  end

  def install
    bin.install "refactor"
  end

  test do
    assert_path_exists bin/"refactor"
  end
end
